### PR TITLE
fixed a bug in the recommendation.py model to add receiver and giver

### LINKED ISSUE #22: REPORT: Completed orders
As a business analyst, I would like to see an HTML report showing all orders that have been paid for.

* Order Id
* Customer name
* Total paid for the order
* Payment type

### PR DESCRIPTION
**Pull request by nrg51098**
Description of PR that completes issue here...

## Changes

- Item 1
- Item 2
- Item 3

## Requests / Responses

If this PR contains code that defines a new request/response, or changes an existing one, please put the JSON representations here.

**Request**

POST `/products` Creates a new product

```json
{
    "title": "Kite",
    "product_type_id": 1,
    "description": "Red. It flies high.",
    "quantity": 5
}
```

**Response**

HTTP/1.1 201 OK

```json
{
    "id": 54,
    "title": "Kite",
    "product_type_id": 1,
    "description": "Red. It flies high.",
    "quantity": 5
}
```

## Testing

Description of how to test code...

- [ ] Run migrations
- [ ] Run test suite
- [ ] Seed database

## Related Issues

- Fixes #85
- Fixes #22

### CODE REVIEW

**Comment by mitchellblom** [comment]
Please edit your PR description to match what changes have been made to your PR.

**Comment by nrg51098** [comment]
> Please edit your PR description to match what changes have been made to your PR.

Just fixed that.

**Comment by mitchellblom** [comment]
Your PR description is still just the template. Headed to your breakout room now to talk it out.

**Comment by nrg51098** [comment]
Description of PR that completes issue here...

## Changes

- Changed the recommendation.py model to reflect the receiver and giver

## Requests/Responses
-Did not make any changes to requests and responses

## Testing

Description of how to test code...

- [ ] Run migrations
- [ ] Run test suite
- [ ] Seed database
- [ ] Run the http-server

## Related Issues

No ticket fixed - only finished setup.

**Review by mitchellblom — APPROVED** [review]

**Pull request merged**
